#!/bin/bash

SPECSPATH=./Templates
PWD=$(pwd)

function showdoc()
{
	echo -e "rpmss is a RPM Sample Specs tool\n"
    echo -e "\$rpmss [options or samplename]"
	echo -e "options:"
	echo -e "  -i\t\t-- interactive mode"
	echo -e "  -l|--list\t-- list of available specs"
	echo -e "  -h|--help\t-- show this message\n"
	echo -e "samplename:"
	echo -e "  Name from \"rpmss --list\""
	echo -e "  If no name (epmty value)\t-- copying a simple.spec by default in a PWD dir"
}

function is_spec_exist()
{
  if [ -f "$SPECSPATH/$spectempl.spec" ];
	  then echo " You choosed a $spectempl "
	  else echo " $spectempl doesn't exist"
		   exit 1
  fi
}

function interactive()
{
  echo " Please, enter the Name of Spec: "
  read spectempl
}

function specs_list()
{
  if [ -d $SPECSPATH ];
	  then ls $SPECSPATH | sed 's%\.spec%%'
	  else echo " SPECSPATH doesn't exist "
		   exit 1
  fi
}

function get_from_list()
{
  echo $1
  #get list of specs
  if [ -d $SPECSPATH ];
	  then specslist=$(ls $SPECSPATH | sed 's%\.spec%%')
	  else echo " SPECSPATH doesn't xist "
		   exit 1
  fi
  
  #find the spec
  for i in $specslist; do
	if [ "$i" == "$1" ]; then
	   cp $SPECSPATH/$i.spec $PWD && return 0 || return 1
	fi
  done
}

function default_spec()
{
  cp $SPECSPATH/simple.spec $PWD
  echo "$PWD/simple.spec has create"
}

function cp_choosed_spec()
{
  no_spec_in_pwd $spectempl &&\
	cp $SPECSPATH/$spectempl.spec $PWD && echo "$PWD/$spectempl.spec has create"
}

function no_spec_in_pwd()
{
  if [ -f "$PWD/$1.spec" ];  then
	echo "$PWD/$1.spec already exist. Move or rm it."
	return 1
  else
	return 0
  fi
}

#main loop

case "$1" in
	-i)
	    specs_list
		interactive
		is_spec_exist
		cp_choosed_spec 
		;;
	-l|--list)
		specs_list	
		;;
	-h|--help)
		showdoc	
		;;
	*)
	    get_from_list "$1" && default_spec
esac

exit 0
